// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IEAGrtfohSkfiq8qTfQTWqL4MRFR2Wg',
    appId: '1:647434495305:android:8440c0d102b978e8baa698',
    messagingSenderId: '647434495305',
    projectId: 'event-planing-seka',
    storageBucket: 'event-planing-seka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXI-TNnMdZl3euATwm9yh7vK9JXZRgZg',
    appId: '1:647434495305:ios:1b96297ae6e83602baa698',
    messagingSenderId: '647434495305',
    projectId: 'event-planing-seka',
    storageBucket: 'event-planing-seka.firebasestorage.app',
    iosBundleId: 'com.example.shehabEvent',
  );
}
